### ISSUE TITLE
[Bug] Optimal Aim Red Box completely covers screen when fighting/riding ender dragon

### ISSUE THREAD

**Issue by Lucipo** [sootysplash/optimal-aim#3]
clip: https://medal.tv/games/minecraft/clips/ivXCPaPPR4Qc2kxPa/d1337ITtti6E?invite=cr-MSxGMUMsMTA1ODAwNzcs

version: quilt 1.20.6
mod version: v1.0

**Comment by sootysplash** [comment]
Fixed in this [version](https://modrinth.com/mod/optimal-aim/version/1.0.4)

Here's a clip of the new behavior: https://streamable.com/e3fqfl
